FROM openjdk:12

EXPOSE 8080
WORKDIR /salve-minha-carteira-back
ENTRYPOINT /bin/bash -c "chmod +x /salve-minha-carteira-back/extras/docker/entrypoint.sh && /salve-minha-carteira-back/extras/docker/entrypoint.sh"