use salve-minha-carteira-db;
INSERT INTO empresa (nome) VALUES ('3M');
INSERT INTO empresa (nome) VALUES ('ABBOTT');
INSERT INTO empresa (nome) VALUES ('ABBVIE');
INSERT INTO empresa (nome) VALUES ('ABC BRASIL');
INSERT INTO empresa (nome) VALUES ('ACCENTURE');
INSERT INTO empresa (nome) VALUES ('ACO ALTONA');
INSERT INTO empresa (nome) VALUES ('ACTIVISION');
INSERT INTO empresa (nome) VALUES ('ADOBE INC');
INSERT INTO empresa (nome) VALUES ('ADVANCED-DH');
INSERT INTO empresa (nome) VALUES ('AES TIETE E');
INSERT INTO empresa (nome) VALUES ('AFLUENTE T');
INSERT INTO empresa (nome) VALUES ('AGCONCESSOES');
INSERT INTO empresa (nome) VALUES ('AIG GROUP');
INSERT INTO empresa (nome) VALUES ('ALFA CONSORC');
INSERT INTO empresa (nome) VALUES ('ALFA FINANC');
INSERT INTO empresa (nome) VALUES ('ALFA HOLDING');
INSERT INTO empresa (nome) VALUES ('ALFA INVEST');
INSERT INTO empresa (nome) VALUES ('ALIANSCE');
INSERT INTO empresa (nome) VALUES ('ALIANSCSONAE');
INSERT INTO empresa (nome) VALUES ('ALIPERTI');
INSERT INTO empresa (nome) VALUES ('ALLIAR');
INSERT INTO empresa (nome) VALUES ('ALPARGATAS');
INSERT INTO empresa (nome) VALUES ('ALPER S.A.');
INSERT INTO empresa (nome) VALUES ('ALPHABET');
INSERT INTO empresa (nome) VALUES ('ALTRIA GROUP');
INSERT INTO empresa (nome) VALUES ('ALUPAR');
INSERT INTO empresa (nome) VALUES ('AMAZON');
INSERT INTO empresa (nome) VALUES ('AMAZONIA');
INSERT INTO empresa (nome) VALUES ('AMBEV S/A');
INSERT INTO empresa (nome) VALUES ('AMERICAN AIR');
INSERT INTO empresa (nome) VALUES ('AMERICAN EXP');
INSERT INTO empresa (nome) VALUES ('AMGEN');
INSERT INTO empresa (nome) VALUES ('AMPLA ENERG');
INSERT INTO empresa (nome) VALUES ('ANIMA');
INSERT INTO empresa (nome) VALUES ('APPLE');
INSERT INTO empresa (nome) VALUES ('APTIV PLC');
INSERT INTO empresa (nome) VALUES ('ARCELOR');
INSERT INTO empresa (nome) VALUES ('ARCONIC');
INSERT INTO empresa (nome) VALUES ('AREZZO CO');
INSERT INTO empresa (nome) VALUES ('ARMSTRONG');
INSERT INTO empresa (nome) VALUES ('ATOMPAR');
INSERT INTO empresa (nome) VALUES ('ATT INC');
INSERT INTO empresa (nome) VALUES ('AUTOMATIC DT');
INSERT INTO empresa (nome) VALUES ('AUTOZONE INC');
INSERT INTO empresa (nome) VALUES ('AVON');
INSERT INTO empresa (nome) VALUES ('AZEVEDO');
INSERT INTO empresa (nome) VALUES ('AZUL');
INSERT INTO empresa (nome) VALUES ('B2W DIGITAL');
INSERT INTO empresa (nome) VALUES ('B3');
INSERT INTO empresa (nome) VALUES ('BAHEMA');
INSERT INTO empresa (nome) VALUES ('BANCO INTER');
INSERT INTO empresa (nome) VALUES ('BANCO PAN');
INSERT INTO empresa (nome) VALUES ('BANESE');
INSERT INTO empresa (nome) VALUES ('BANESTES');
INSERT INTO empresa (nome) VALUES ('BANK AMERICA');
INSERT INTO empresa (nome) VALUES ('BANPARA');
INSERT INTO empresa (nome) VALUES ('BANRISUL');
INSERT INTO empresa (nome) VALUES ('BARDELLA');
INSERT INTO empresa (nome) VALUES ('BATTISTELLA');
INSERT INTO empresa (nome) VALUES ('BAUMER');
INSERT INTO empresa (nome) VALUES ('BB ETF SP DV');
INSERT INTO empresa (nome) VALUES ('BBSEGURIDADE');
INSERT INTO empresa (nome) VALUES ('BERKSHIRE');
INSERT INTO empresa (nome) VALUES ('BEST BUY');
INSERT INTO empresa (nome) VALUES ('BIC MONARK');
INSERT INTO empresa (nome) VALUES ('BIOGEN');
INSERT INTO empresa (nome) VALUES ('BIOMM');
INSERT INTO empresa (nome) VALUES ('BIOSEV');
INSERT INTO empresa (nome) VALUES ('BIOTOSCANA');
INSERT INTO empresa (nome) VALUES ('BK BRASIL');
INSERT INTO empresa (nome) VALUES ('BLACKROCK');
INSERT INTO empresa (nome) VALUES ('BNY MELLON');
INSERT INTO empresa (nome) VALUES ('BOEING');
INSERT INTO empresa (nome) VALUES ('BOMBRIL');
INSERT INTO empresa (nome) VALUES ('BOOKING');
INSERT INTO empresa (nome) VALUES ('BOSTON PROP');
INSERT INTO empresa (nome) VALUES ('BRADESCO');
INSERT INTO empresa (nome) VALUES ('BRADESPAR');
INSERT INTO empresa (nome) VALUES ('BRASIL');
INSERT INTO empresa (nome) VALUES ('BRASILAGRO');
INSERT INTO empresa (nome) VALUES ('BRASKEM');
INSERT INTO empresa (nome) VALUES ('BRB BANCO');
INSERT INTO empresa (nome) VALUES ('BR BROKERS');
INSERT INTO empresa (nome) VALUES ('BRF SA');
INSERT INTO empresa (nome) VALUES ('BRISTOLMYERS');
INSERT INTO empresa (nome) VALUES ('BR MALLS PAR');
INSERT INTO empresa (nome) VALUES ('BROADCOM INC');
INSERT INTO empresa (nome) VALUES ('BR PHARMA');
INSERT INTO empresa (nome) VALUES ('BR PROPERT');
INSERT INTO empresa (nome) VALUES ('BTGP BANCO');
INSERT INTO empresa (nome) VALUES ('CAIXAETFXBOV');
INSERT INTO empresa (nome) VALUES ('CAMBUCI');
INSERT INTO empresa (nome) VALUES ('CAMIL');
INSERT INTO empresa (nome) VALUES ('CANAD NATION');
INSERT INTO empresa (nome) VALUES ('CANAD PACIFI');
INSERT INTO empresa (nome) VALUES ('CAPITAL ONE');
INSERT INTO empresa (nome) VALUES ('CAPITALPART');
INSERT INTO empresa (nome) VALUES ('CAPRI HOLDI');
INSERT INTO empresa (nome) VALUES ('CARREFOUR BR');
INSERT INTO empresa (nome) VALUES ('CARTERS INC');
INSERT INTO empresa (nome) VALUES ('CASAN');
INSERT INTO empresa (nome) VALUES ('CATERPILLAR');
INSERT INTO empresa (nome) VALUES ('CCR SA');
INSERT INTO empresa (nome) VALUES ('CCX CARVAO');
INSERT INTO empresa (nome) VALUES ('CEB');
INSERT INTO empresa (nome) VALUES ('CEDRO');
INSERT INTO empresa (nome) VALUES ('CEEE-D');
INSERT INTO empresa (nome) VALUES ('CEEE-GT');
INSERT INTO empresa (nome) VALUES ('CEG');
INSERT INTO empresa (nome) VALUES ('CELESC');
INSERT INTO empresa (nome) VALUES ('CELGENE CORP');
INSERT INTO empresa (nome) VALUES ('CELGPAR');
INSERT INTO empresa (nome) VALUES ('CELPA');
INSERT INTO empresa (nome) VALUES ('CELPE');
INSERT INTO empresa (nome) VALUES ('CELUL IRANI');
INSERT INTO empresa (nome) VALUES ('CEMAR');
INSERT INTO empresa (nome) VALUES ('CEMEPE');
INSERT INTO empresa (nome) VALUES ('CEMIG');
INSERT INTO empresa (nome) VALUES ('CENTAURO');
INSERT INTO empresa (nome) VALUES ('CESP');
INSERT INTO empresa (nome) VALUES ('CHARTER COMM');
INSERT INTO empresa (nome) VALUES ('CHESAPEAKE');
INSERT INTO empresa (nome) VALUES ('CHEVRON');
INSERT INTO empresa (nome) VALUES ('CHURCH DWIGH');
INSERT INTO empresa (nome) VALUES ('CIA HERING');
INSERT INTO empresa (nome) VALUES ('CIELO');
INSERT INTO empresa (nome) VALUES ('CINCINNATI');
INSERT INTO empresa (nome) VALUES ('CISCO');
INSERT INTO empresa (nome) VALUES ('CITIGROUP');
INSERT INTO empresa (nome) VALUES ('CLOROX CO');
INSERT INTO empresa (nome) VALUES ('CME GROUP');
INSERT INTO empresa (nome) VALUES ('COCA COLA');
INSERT INTO empresa (nome) VALUES ('COELBA');
INSERT INTO empresa (nome) VALUES ('COELCE');
INSERT INTO empresa (nome) VALUES ('COGNA ON');
INSERT INTO empresa (nome) VALUES ('COGNIZANT');
INSERT INTO empresa (nome) VALUES ('COLGATE');
INSERT INTO empresa (nome) VALUES ('COMCAST');
INSERT INTO empresa (nome) VALUES ('COMGAS');
INSERT INTO empresa (nome) VALUES ('CONST A LIND');
INSERT INTO empresa (nome) VALUES ('CONSTELLATIO');
INSERT INTO empresa (nome) VALUES ('COPASA');
INSERT INTO empresa (nome) VALUES ('COPEL');
INSERT INTO empresa (nome) VALUES ('COPHILLIPS');
INSERT INTO empresa (nome) VALUES ('COR RIBEIRO');
INSERT INTO empresa (nome) VALUES ('COSAN');
INSERT INTO empresa (nome) VALUES ('COSAN LOG');
INSERT INTO empresa (nome) VALUES ('COSERN');
INSERT INTO empresa (nome) VALUES ('COSTCO');
INSERT INTO empresa (nome) VALUES ('COTEMINAS');
INSERT INTO empresa (nome) VALUES ('COTY INC');
INSERT INTO empresa (nome) VALUES ('CPFL ENERGIA');
INSERT INTO empresa (nome) VALUES ('CPFL RENOVAV');
INSERT INTO empresa (nome) VALUES ('CR2');
INSERT INTO empresa (nome) VALUES ('CREDIT ACCEP');
INSERT INTO empresa (nome) VALUES ('CRISTAL');
INSERT INTO empresa (nome) VALUES ('CSU CARDSYST');
INSERT INTO empresa (nome) VALUES ('CSX CORP');
INSERT INTO empresa (nome) VALUES ('CVC BRASIL');
INSERT INTO empresa (nome) VALUES ('CVS HEALTH');
INSERT INTO empresa (nome) VALUES ('CYRE COM-CCP');
INSERT INTO empresa (nome) VALUES ('CYRELA REALT');
INSERT INTO empresa (nome) VALUES ('DANAHER CORP');
INSERT INTO empresa (nome) VALUES ('DASA');
INSERT INTO empresa (nome) VALUES ('DAVITA INC');
INSERT INTO empresa (nome) VALUES ('DEERE CO');
INSERT INTO empresa (nome) VALUES ('DELTA');
INSERT INTO empresa (nome) VALUES ('DENTSPLY SIR');
INSERT INTO empresa (nome) VALUES ('DEUTSCHE AK');
INSERT INTO empresa (nome) VALUES ('DIMED');
INSERT INTO empresa (nome) VALUES ('DIRECIONAL');
INSERT INTO empresa (nome) VALUES ('DISCOVERY IN');
INSERT INTO empresa (nome) VALUES ('DOHLER');
INSERT INTO empresa (nome) VALUES ('DOLLAR GENER');
INSERT INTO empresa (nome) VALUES ('DOLLAR TREE');
INSERT INTO empresa (nome) VALUES ('DOMMO');
INSERT INTO empresa (nome) VALUES ('DOWDUPONT');
INSERT INTO empresa (nome) VALUES ('DTCOM-DIRECT');
INSERT INTO empresa (nome) VALUES ('DUKE ENERGY');
INSERT INTO empresa (nome) VALUES ('DUPONT N INC');
INSERT INTO empresa (nome) VALUES ('DURATEX');
INSERT INTO empresa (nome) VALUES ('EBAY');
INSERT INTO empresa (nome) VALUES ('ECORODOVIAS');
INSERT INTO empresa (nome) VALUES ('ELECTR ARTS');
INSERT INTO empresa (nome) VALUES ('ELEKEIROZ');
INSERT INTO empresa (nome) VALUES ('ELEKTRO');
INSERT INTO empresa (nome) VALUES ('ELETROBRAS');
INSERT INTO empresa (nome) VALUES ('ELETROPAR');
INSERT INTO empresa (nome) VALUES ('ELETROPAULO');
INSERT INTO empresa (nome) VALUES ('EMAE');
INSERT INTO empresa (nome) VALUES ('EMBRAER');
INSERT INTO empresa (nome) VALUES ('ENAUTA PART');
INSERT INTO empresa (nome) VALUES ('ENCORPAR');
INSERT INTO empresa (nome) VALUES ('ENERGIAS BR');
INSERT INTO empresa (nome) VALUES ('ENERGISA');
INSERT INTO empresa (nome) VALUES ('ENERGISA MT');
INSERT INTO empresa (nome) VALUES ('ENEVA');
INSERT INTO empresa (nome) VALUES ('ENGIE BRASIL');
INSERT INTO empresa (nome) VALUES ('EQUATORIAL');
INSERT INTO empresa (nome) VALUES ('EQUINIX INC');
INSERT INTO empresa (nome) VALUES ('ESTACIO PART');
INSERT INTO empresa (nome) VALUES ('ESTEE LAUDER');
INSERT INTO empresa (nome) VALUES ('ESTRELA');
INSERT INTO empresa (nome) VALUES ('ETERNIT');
INSERT INTO empresa (nome) VALUES ('ETF BRAD BOV');
INSERT INTO empresa (nome) VALUES ('EUCATEX');
INSERT INTO empresa (nome) VALUES ('EVEN');
INSERT INTO empresa (nome) VALUES ('EXCELSIOR');
INSERT INTO empresa (nome) VALUES ('EXPEDIA GROU');
INSERT INTO empresa (nome) VALUES ('EXXON MOBIL');
INSERT INTO empresa (nome) VALUES ('EZTEC');
INSERT INTO empresa (nome) VALUES ('FACEBOOK');
INSERT INTO empresa (nome) VALUES ('FASTENAL');
INSERT INTO empresa (nome) VALUES ('FEDEX CORP');
INSERT INTO empresa (nome) VALUES ('FEMSA');
INSERT INTO empresa (nome) VALUES ('FERBASA');
INSERT INTO empresa (nome) VALUES ('FER HERINGER');
INSERT INTO empresa (nome) VALUES ('FIBAM');
INSERT INTO empresa (nome) VALUES ('FIBRIA');
INSERT INTO empresa (nome) VALUES ('FIFTH THIRD');
INSERT INTO empresa (nome) VALUES ('FINAM');
INSERT INTO empresa (nome) VALUES ('FINOR');
INSERT INTO empresa (nome) VALUES ('FIP CONQUEST');
INSERT INTO empresa (nome) VALUES ('FIP IE II');
INSERT INTO empresa (nome) VALUES ('FIP IE III');
INSERT INTO empresa (nome) VALUES ('FIP PORT SUD');
INSERT INTO empresa (nome) VALUES ('FIP XP INFRA');
INSERT INTO empresa (nome) VALUES ('FIP XP OMEGA');
INSERT INTO empresa (nome) VALUES ('FIRST SOLAR');
INSERT INTO empresa (nome) VALUES ('FISET FL REF');
INSERT INTO empresa (nome) VALUES ('FISET PESCA');
INSERT INTO empresa (nome) VALUES ('FISET TUR');
INSERT INTO empresa (nome) VALUES ('FLEETCOR TEC');
INSERT INTO empresa (nome) VALUES ('FLEURY');
INSERT INTO empresa (nome) VALUES ('FORD MOTORS');
INSERT INTO empresa (nome) VALUES ('FORJA TAURUS');
INSERT INTO empresa (nome) VALUES ('FOX CORP');
INSERT INTO empresa (nome) VALUES ('FRAS-LE');
INSERT INTO empresa (nome) VALUES ('FREEPORT');
INSERT INTO empresa (nome) VALUES ('FUNDES');
INSERT INTO empresa (nome) VALUES ('GAFISA');
INSERT INTO empresa (nome) VALUES ('GAP');
INSERT INTO empresa (nome) VALUES ('GE');
INSERT INTO empresa (nome) VALUES ('GEN DYNAMICS');
INSERT INTO empresa (nome) VALUES ('GENERAL MOT');
INSERT INTO empresa (nome) VALUES ('GENERALSHOPP');
INSERT INTO empresa (nome) VALUES ('GEOPARK LTD');
INSERT INTO empresa (nome) VALUES ('GERDAU');
INSERT INTO empresa (nome) VALUES ('GERDAU MET');
INSERT INTO empresa (nome) VALUES ('GER PARANAP');
INSERT INTO empresa (nome) VALUES ('GILEAD');
INSERT INTO empresa (nome) VALUES ('GOL');
INSERT INTO empresa (nome) VALUES ('GOLDMANSACHS');
INSERT INTO empresa (nome) VALUES ('GPC PART');
INSERT INTO empresa (nome) VALUES ('GP INVEST');
INSERT INTO empresa (nome) VALUES ('GRAZZIOTIN');
INSERT INTO empresa (nome) VALUES ('GRENDENE');
INSERT INTO empresa (nome) VALUES ('GUARARAPES');
INSERT INTO empresa (nome) VALUES ('HABITASUL');
INSERT INTO empresa (nome) VALUES ('HAGA S/A');
INSERT INTO empresa (nome) VALUES ('HALLIBURTON');
INSERT INTO empresa (nome) VALUES ('HANOVER INSU');
INSERT INTO empresa (nome) VALUES ('HAPVIDA');
INSERT INTO empresa (nome) VALUES ('HELBOR');
INSERT INTO empresa (nome) VALUES ('HERCULES');
INSERT INTO empresa (nome) VALUES ('HERSHEY CO');
INSERT INTO empresa (nome) VALUES ('HOME DEPOT');
INSERT INTO empresa (nome) VALUES ('HONEYWELL');
INSERT INTO empresa (nome) VALUES ('HOTEIS OTHON');
INSERT INTO empresa (nome) VALUES ('HP COMPANY');
INSERT INTO empresa (nome) VALUES ('HYPERA');
INSERT INTO empresa (nome) VALUES ('IBM');
INSERT INTO empresa (nome) VALUES ('IBOVESPA');
INSERT INTO empresa (nome) VALUES ('IDEIASNET');
INSERT INTO empresa (nome) VALUES ('IGB S/A');
INSERT INTO empresa (nome) VALUES ('IGUATEMI');
INSERT INTO empresa (nome) VALUES ('IHPARDINI');
INSERT INTO empresa (nome) VALUES ('IMC S/A');
INSERT INTO empresa (nome) VALUES ('INDS ROMI');
INSERT INTO empresa (nome) VALUES ('INDUSVAL');
INSERT INTO empresa (nome) VALUES ('INEPAR');
INSERT INTO empresa (nome) VALUES ('INTEL');
INSERT INTO empresa (nome) VALUES ('INTERMEDICA');
INSERT INTO empresa (nome) VALUES ('INTUIT INC');
INSERT INTO empresa (nome) VALUES ('INVEST BCORP');
INSERT INTO empresa (nome) VALUES ('IOCHP-MAXION');
INSERT INTO empresa (nome) VALUES ('IRBBRASIL RE');
INSERT INTO empresa (nome) VALUES ('ISHARES BOVA');
INSERT INTO empresa (nome) VALUES ('ISHARES BRAX');
INSERT INTO empresa (nome) VALUES ('ISHARES ECOO');
INSERT INTO empresa (nome) VALUES ('ISHARE SP500');
INSERT INTO empresa (nome) VALUES ('ISHARES SMAL');
INSERT INTO empresa (nome) VALUES ('ITAUSA');
INSERT INTO empresa (nome) VALUES ('ITAUTEC');
INSERT INTO empresa (nome) VALUES ('ITAUUNIBANCO');
INSERT INTO empresa (nome) VALUES ('IT NOW IBOV');
INSERT INTO empresa (nome) VALUES ('IT NOW IDIV');
INSERT INTO empresa (nome) VALUES ('IT NOW IFNC');
INSERT INTO empresa (nome) VALUES ('IT NOW IGCT');
INSERT INTO empresa (nome) VALUES ('IT NOW IMAT');
INSERT INTO empresa (nome) VALUES ('IT NOW ISE');
INSERT INTO empresa (nome) VALUES ('IT NOW PIBB');
INSERT INTO empresa (nome) VALUES ('IT NOW SPXI');
INSERT INTO empresa (nome) VALUES ('J B DUARTE');
INSERT INTO empresa (nome) VALUES ('JBS');
INSERT INTO empresa (nome) VALUES ('JEREISSATI');
INSERT INTO empresa (nome) VALUES ('JHSF PART');
INSERT INTO empresa (nome) VALUES ('JOAO FORTES');
INSERT INTO empresa (nome) VALUES ('JOHNSON');
INSERT INTO empresa (nome) VALUES ('JOSAPAR');
INSERT INTO empresa (nome) VALUES ('JPMORGAN');
INSERT INTO empresa (nome) VALUES ('JSL');
INSERT INTO empresa (nome) VALUES ('KARSTEN');
INSERT INTO empresa (nome) VALUES ('KEMPER CORP');
INSERT INTO empresa (nome) VALUES ('KEPLER WEBER');
INSERT INTO empresa (nome) VALUES ('KIMBERLY CL');
INSERT INTO empresa (nome) VALUES ('KINDER MORGA');
INSERT INTO empresa (nome) VALUES ('KLABIN S/A');
INSERT INTO empresa (nome) VALUES ('KRAFT HEINZ');
INSERT INTO empresa (nome) VALUES ('KROTON');
INSERT INTO empresa (nome) VALUES ('L BRANDS');
INSERT INTO empresa (nome) VALUES ('LE LIS BLANC');
INSERT INTO empresa (nome) VALUES ('LIBERTY BROA');
INSERT INTO empresa (nome) VALUES ('LIBERTY MEDI');
INSERT INTO empresa (nome) VALUES ('LIGHT S/A');
INSERT INTO empresa (nome) VALUES ('LILLY');
INSERT INTO empresa (nome) VALUES ('LINX');
INSERT INTO empresa (nome) VALUES ('LIQ');
INSERT INTO empresa (nome) VALUES ('LOCALIZA');
INSERT INTO empresa (nome) VALUES ('LOCAMERICA');
INSERT INTO empresa (nome) VALUES ('LOCKHEED');
INSERT INTO empresa (nome) VALUES ('LOG COM PROP');
INSERT INTO empresa (nome) VALUES ('LOG-IN');
INSERT INTO empresa (nome) VALUES ('LOJAS AMERIC');
INSERT INTO empresa (nome) VALUES ('LOJAS HERING');
INSERT INTO empresa (nome) VALUES ('LOJAS MARISA');
INSERT INTO empresa (nome) VALUES ('LOJAS RENNER');
INSERT INTO empresa (nome) VALUES ('LONGDIS');
INSERT INTO empresa (nome) VALUES ('LOPES BRASIL');
INSERT INTO empresa (nome) VALUES ('LOWES COMPA');
INSERT INTO empresa (nome) VALUES ('LUPATECH');
INSERT INTO empresa (nome) VALUES ('MACY S');
INSERT INTO empresa (nome) VALUES ('MAGAZ LUIZA');
INSERT INTO empresa (nome) VALUES ('MAGNESITA SA');
INSERT INTO empresa (nome) VALUES ('MANGELS INDL');
INSERT INTO empresa (nome) VALUES ('MARCOPOLO');
INSERT INTO empresa (nome) VALUES ('MARFRIG');
INSERT INTO empresa (nome) VALUES ('MARKEL CORP');
INSERT INTO empresa (nome) VALUES ('MASTERCARD');
INSERT INTO empresa (nome) VALUES ('MCDONALDS');
INSERT INTO empresa (nome) VALUES ('M.DIASBRANCO');
INSERT INTO empresa (nome) VALUES ('MEDTRONIC');
INSERT INTO empresa (nome) VALUES ('MELHOR SP');
INSERT INTO empresa (nome) VALUES ('MENDES JR');
INSERT INTO empresa (nome) VALUES ('MERCADOLIBRE');
INSERT INTO empresa (nome) VALUES ('MERC BRASIL');
INSERT INTO empresa (nome) VALUES ('MERC FINANC');
INSERT INTO empresa (nome) VALUES ('MERC INVEST');
INSERT INTO empresa (nome) VALUES ('MERCK');
INSERT INTO empresa (nome) VALUES ('METALFRIO');
INSERT INTO empresa (nome) VALUES ('METAL IGUACU');
INSERT INTO empresa (nome) VALUES ('METAL LEVE');
INSERT INTO empresa (nome) VALUES ('METISA');
INSERT INTO empresa (nome) VALUES ('METLIFE INC');
INSERT INTO empresa (nome) VALUES ('MICRON TECHN');
INSERT INTO empresa (nome) VALUES ('MICROSOFT');
INSERT INTO empresa (nome) VALUES ('MILLS');
INSERT INTO empresa (nome) VALUES ('MINASMAQUINA');
INSERT INTO empresa (nome) VALUES ('MINERVA');
INSERT INTO empresa (nome) VALUES ('MINUPAR');
INSERT INTO empresa (nome) VALUES ('MMX MINER');
INSERT INTO empresa (nome) VALUES ('MONDELEZ INT');
INSERT INTO empresa (nome) VALUES ('MONT ARANHA');
INSERT INTO empresa (nome) VALUES ('MOODYS CORP');
INSERT INTO empresa (nome) VALUES ('MORGAN STAN');
INSERT INTO empresa (nome) VALUES ('MOSAIC CO');
INSERT INTO empresa (nome) VALUES ('MOVIDA');
INSERT INTO empresa (nome) VALUES ('MRS LOGIST');
INSERT INTO empresa (nome) VALUES ('MRV');
INSERT INTO empresa (nome) VALUES ('MULTIPLAN');
INSERT INTO empresa (nome) VALUES ('MULTIPLUS');
INSERT INTO empresa (nome) VALUES ('MUNDIAL');
INSERT INTO empresa (nome) VALUES ('NADIR FIGUEI');
INSERT INTO empresa (nome) VALUES ('NATURA');
INSERT INTO empresa (nome) VALUES ('NEOENERGIA');
INSERT INTO empresa (nome) VALUES ('NETFLIX');
INSERT INTO empresa (nome) VALUES ('NEXTERA ENER');
INSERT INTO empresa (nome) VALUES ('NIKE');
INSERT INTO empresa (nome) VALUES ('NORD BRASIL');
INSERT INTO empresa (nome) VALUES ('NORDON MET');
INSERT INTO empresa (nome) VALUES ('NORTHROP GRU');
INSERT INTO empresa (nome) VALUES ('NUTRIPLANT');
INSERT INTO empresa (nome) VALUES ('NVIDIA CORP');
INSERT INTO empresa (nome) VALUES ('OCCIDENT PTR');
INSERT INTO empresa (nome) VALUES ('ODONTOPREV');
INSERT INTO empresa (nome) VALUES ('OGX PETROLEO');
INSERT INTO empresa (nome) VALUES ('OI');
INSERT INTO empresa (nome) VALUES ('OMEGA GER');
INSERT INTO empresa (nome) VALUES ('ORACLE');
INSERT INTO empresa (nome) VALUES ('OREILLY AUT');
INSERT INTO empresa (nome) VALUES ('OSX BRASIL');
INSERT INTO empresa (nome) VALUES ('OUROFINO S/A');
INSERT INTO empresa (nome) VALUES ('P.ACUCAR-CBD');
INSERT INTO empresa (nome) VALUES ('PANATLANTICA');
INSERT INTO empresa (nome) VALUES ('PAR AL BAHIA');
INSERT INTO empresa (nome) VALUES ('PARANAPANEMA');
INSERT INTO empresa (nome) VALUES ('PAYPAL HOLD');
INSERT INTO empresa (nome) VALUES ('PDG REALT');
INSERT INTO empresa (nome) VALUES ('PEPSICO INC');
INSERT INTO empresa (nome) VALUES ('PET MANGUINH');
INSERT INTO empresa (nome) VALUES ('PETROBRAS');
INSERT INTO empresa (nome) VALUES ('PETROBRAS BR');
INSERT INTO empresa (nome) VALUES ('PETRORIO');
INSERT INTO empresa (nome) VALUES ('PETTENATI');
INSERT INTO empresa (nome) VALUES ('PFIZER');
INSERT INTO empresa (nome) VALUES ('PG');
INSERT INTO empresa (nome) VALUES ('PHILIP MORRI');
INSERT INTO empresa (nome) VALUES ('PINE');
INSERT INTO empresa (nome) VALUES ('PLASCAR PART');
INSERT INTO empresa (nome) VALUES ('PNCFNANCIAL');
INSERT INTO empresa (nome) VALUES ('POMIFRUTAS');
INSERT INTO empresa (nome) VALUES ('PORTOBELLO');
INSERT INTO empresa (nome) VALUES ('PORTO SEGURO');
INSERT INTO empresa (nome) VALUES ('PORTO VM');
INSERT INTO empresa (nome) VALUES ('POSITIVO TEC');
INSERT INTO empresa (nome) VALUES ('PPLA');
INSERT INTO empresa (nome) VALUES ('PROFARMA');
INSERT INTO empresa (nome) VALUES ('QGEP PART');
INSERT INTO empresa (nome) VALUES ('QUALCOMM');
INSERT INTO empresa (nome) VALUES ('QUALICORP');
INSERT INTO empresa (nome) VALUES ('RAIADROGASIL');
INSERT INTO empresa (nome) VALUES ('RANDON PART');
INSERT INTO empresa (nome) VALUES ('RECRUSUL');
INSERT INTO empresa (nome) VALUES ('REDE ENERGIA');
INSERT INTO empresa (nome) VALUES ('REGENERON PH');
INSERT INTO empresa (nome) VALUES ('RENOVA');
INSERT INTO empresa (nome) VALUES ('RIOSULENSE');
INSERT INTO empresa (nome) VALUES ('RNI');
INSERT INTO empresa (nome) VALUES ('ROSSI RESID');
INSERT INTO empresa (nome) VALUES ('ROSS STORES');
INSERT INTO empresa (nome) VALUES ('RUMO S.A.');
INSERT INTO empresa (nome) VALUES ('SABESP');
INSERT INTO empresa (nome) VALUES ('SALESFORCE');
INSERT INTO empresa (nome) VALUES ('SANEPAR');
INSERT INTO empresa (nome) VALUES ('SANSUY');
INSERT INTO empresa (nome) VALUES ('SANTANDER BR');
INSERT INTO empresa (nome) VALUES ('SANTANENSE');
INSERT INTO empresa (nome) VALUES ('SANTOS BRP');
INSERT INTO empresa (nome) VALUES ('SAO CARLOS');
INSERT INTO empresa (nome) VALUES ('SAO MARTINHO');
INSERT INTO empresa (nome) VALUES ('SARAIVA LIVR');
INSERT INTO empresa (nome) VALUES ('SCHLUMBERGER');
INSERT INTO empresa (nome) VALUES ('SCHULZ');
INSERT INTO empresa (nome) VALUES ('SCHWAB');
INSERT INTO empresa (nome) VALUES ('SEG AL BAHIA');
INSERT INTO empresa (nome) VALUES ('SENIOR SOL');
INSERT INTO empresa (nome) VALUES ('SER EDUCA');
INSERT INTO empresa (nome) VALUES ('SID NACIONAL');
INSERT INTO empresa (nome) VALUES ('SIERRABRASIL');
INSERT INTO empresa (nome) VALUES ('SIGNATURE BK');
INSERT INTO empresa (nome) VALUES ('SIMON PROP');
INSERT INTO empresa (nome) VALUES ('SINQIA');
INSERT INTO empresa (nome) VALUES ('SIRIUS XM HD');
INSERT INTO empresa (nome) VALUES ('SLC AGRICOLA');
INSERT INTO empresa (nome) VALUES ('SMILES');
INSERT INTO empresa (nome) VALUES ('SOMOS EDUCA');
INSERT INTO empresa (nome) VALUES ('SONDOTECNICA');
INSERT INTO empresa (nome) VALUES ('SP GLOBAL');
INSERT INTO empresa (nome) VALUES ('SPRINGER');
INSERT INTO empresa (nome) VALUES ('SPRINGS');
INSERT INTO empresa (nome) VALUES ('SPTURIS');
INSERT INTO empresa (nome) VALUES ('STARBUCKS');
INSERT INTO empresa (nome) VALUES ('STERLING BNC');
INSERT INTO empresa (nome) VALUES ('SUL AMERICA');
INSERT INTO empresa (nome) VALUES ('SUZANO PAPEL');
INSERT INTO empresa (nome) VALUES ('SUZANO S.A.');
INSERT INTO empresa (nome) VALUES ('TAESA');
INSERT INTO empresa (nome) VALUES ('TAPESTRY INC');
INSERT INTO empresa (nome) VALUES ('TARGET CORP');
INSERT INTO empresa (nome) VALUES ('TARPON INV');
INSERT INTO empresa (nome) VALUES ('TECHNOS');
INSERT INTO empresa (nome) VALUES ('TECNISA');
INSERT INTO empresa (nome) VALUES ('TECNOSOLO');
INSERT INTO empresa (nome) VALUES ('TECTOY');
INSERT INTO empresa (nome) VALUES ('TEGMA');
INSERT INTO empresa (nome) VALUES ('TEKA');
INSERT INTO empresa (nome) VALUES ('TEKNO');
INSERT INTO empresa (nome) VALUES ('TELEBRAS');
INSERT INTO empresa (nome) VALUES ('TELEF BRASIL');
INSERT INTO empresa (nome) VALUES ('TENDA');
INSERT INTO empresa (nome) VALUES ('TERRA SANTA');
INSERT INTO empresa (nome) VALUES ('TESLA INC');
INSERT INTO empresa (nome) VALUES ('TEXAS INC');
INSERT INTO empresa (nome) VALUES ('TEX RENAUX');
INSERT INTO empresa (nome) VALUES ('THERMFISCHER');
INSERT INTO empresa (nome) VALUES ('TIFFANY');
INSERT INTO empresa (nome) VALUES ('TIME FOR FUN');
INSERT INTO empresa (nome) VALUES ('TIM PART S/A');
INSERT INTO empresa (nome) VALUES ('TJX COMPANIE');
INSERT INTO empresa (nome) VALUES ('TOTVS');
INSERT INTO empresa (nome) VALUES ('TRAN PAULIST');
INSERT INTO empresa (nome) VALUES ('TRANSOCEAN');
INSERT INTO empresa (nome) VALUES ('TRAVELERS');
INSERT INTO empresa (nome) VALUES ('TREVISA');
INSERT INTO empresa (nome) VALUES ('TRISUL');
INSERT INTO empresa (nome) VALUES ('TRIUNFO PART');
INSERT INTO empresa (nome) VALUES ('TUPY');
INSERT INTO empresa (nome) VALUES ('TWITTER');
INSERT INTO empresa (nome) VALUES ('TYSON FOODS');
INSERT INTO empresa (nome) VALUES ('UBS GROUP');
INSERT INTO empresa (nome) VALUES ('ULTRAPAR');
INSERT INTO empresa (nome) VALUES ('UNICASA');
INSERT INTO empresa (nome) VALUES ('UNIONPACIFIC');
INSERT INTO empresa (nome) VALUES ('UNIPAR');
INSERT INTO empresa (nome) VALUES ('UNITEDHEALTH');
INSERT INTO empresa (nome) VALUES ('UNITED TECH');
INSERT INTO empresa (nome) VALUES ('UPS');
INSERT INTO empresa (nome) VALUES ('US BANCORP');
INSERT INTO empresa (nome) VALUES ('USIMINAS');
INSERT INTO empresa (nome) VALUES ('US STEEL');
INSERT INTO empresa (nome) VALUES ('VALE');
INSERT INTO empresa (nome) VALUES ('VALERO ENER');
INSERT INTO empresa (nome) VALUES ('VALID');
INSERT INTO empresa (nome) VALUES ('VALLEY NTION');
INSERT INTO empresa (nome) VALUES ('VERISIGN INC');
INSERT INTO empresa (nome) VALUES ('VERIZON');
INSERT INTO empresa (nome) VALUES ('VERTEX PHARM');
INSERT INTO empresa (nome) VALUES ('VF CORP');
INSERT INTO empresa (nome) VALUES ('VIACOM INC');
INSERT INTO empresa (nome) VALUES ('VIAVAREJO');
INSERT INTO empresa (nome) VALUES ('VISA INC');
INSERT INTO empresa (nome) VALUES ('VIVARA S.A.');
INSERT INTO empresa (nome) VALUES ('VIVER');
INSERT INTO empresa (nome) VALUES ('VULCABRAS');
INSERT INTO empresa (nome) VALUES ('WALGREENS');
INSERT INTO empresa (nome) VALUES ('WAL MART');
INSERT INTO empresa (nome) VALUES ('WALT DISNEY');
INSERT INTO empresa (nome) VALUES ('WATERS CORP');
INSERT INTO empresa (nome) VALUES ('WEG');
INSERT INTO empresa (nome) VALUES ('WELLS FARGO');
INSERT INTO empresa (nome) VALUES ('WESTERN BCOR');
INSERT INTO empresa (nome) VALUES ('WESTERNUNION');
INSERT INTO empresa (nome) VALUES ('WETZEL S/A');
INSERT INTO empresa (nome) VALUES ('WHIRLPOOL');
INSERT INTO empresa (nome) VALUES ('WILSON SONS');
INSERT INTO empresa (nome) VALUES ('WIZ S.A.');
INSERT INTO empresa (nome) VALUES ('WLM IND COM');
INSERT INTO empresa (nome) VALUES ('XEROX CORP');
INSERT INTO empresa (nome) VALUES ('YDUQS PART');
INSERT INTO empresa (nome) VALUES ('YUM BRANDS');
